export const projects = [
  {
    title: 'Blog-Stories',
    description: "Using React, Node.js, Express & MongoDB post a post of your own for people to see! User can create accounts and manage posts.",
    image: '/images/blog-stories1.png',
    demo: 'https://youtu.be/Of06nl8_TI8',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/vudiep411/blogs-client',
    visit: 'https://regal-sunshine-b112e5.netlify.app/',
    id: 0,
  },
  {
    title: 'Employee Management System',
    description:"Simple HR employee management system with a log in system using React, Express, MySQL & bootstrap.",
    image: '/images/employee1.png',
    tags: ['React', 'Express', 'MySQL', 'Node'],
    source: 'https://github.com/vudiep411/CPSC349-Client',
    demo: 'https://youtu.be/SZ1f2yn9NwU',
    visit: 'https://velvety-rabanadas-dffc6b.netlify.app/',
    id: 1,
  },
  {
    title: 'Dentist Appointment Scheduler',
    description: "A project inspired by my cousin who runs a dentist office but still uses pen and paper for scheduling appointments. This scheduler helps him schedule appointments for patients and save the data in mongodb. It also has an automated send an SMS reminder for patients using Twilio service",
      image: '/images/Calendar.png',
      tags: ['React', 'Node.js', 'Express.js', 'Mongo'],
    source: 'https://github.com/vudiep411/DentistOfficePatientsScheduler',
    demo: 'https://youtu.be/Izv46Q_xSqI',
    visit: 'https://youtu.be/Izv46Q_xSqI',
    id: 2, 
  },
  {
    title: 'Stock Porfolio Management',
    description: "A  commercial  portfolio management system requires numerous complex features to help organizations maintain and manage their financial assets. Fetching real time data from yahoo finance API, Bfinance (Still working on more backtesting features)",
    image: '/images/portfolio.png',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/vudiep411/PorfolioManagement',
    demo: 'https://youtu.be/7oObKx6uIfc',
    visit: 'https://main.d25n7xn7e49jra.amplifyapp.com/',
    id: 3,
  },
  {
    title: 'Ecommerce Website',
    description: "An Online Ecommerce store using Next.js integrated with Stripe for payment method and Sanity for database",
    image: '/images/ecommerce.png',
    tags: ['Sanity', 'Next.js', 'Stripe'],
    source: 'https://github.com/vudiep411/ecommerce-sanity-stripe',
    demo: 'https://youtu.be/6HXfQgtNYnE',
    visit: 'https://ecommerce-sanity-stripe-pi-two.vercel.app/',
    id: 4,
  },
  {
    title: 'QuickVids',
    description: "A social media platform for people to post videos, follows, like and comment similar to Tiktok using next.js for front-end, node.js for back-end, and sanity for database",
    image: '/images/quickvid.png',
    tags: ['Sanity', 'Next.js'],
    source: 'https://github.com/vudiep411/QuickVids-App',
    demo: 'https://github.com/vudiep411/QuickVids-App',
    visit: 'https://quick-vids-app.vercel.app/',
    id: 5,
  },
  {
    title: 'Note-App',
    description: "A note application that allows user to create and save their notes. Sign in, create, edit, delete your personal note.",
    image: '/images/note.png',
    tags: ['React', 'Django', 'SQLite3'],
    source: 'https://github.com/vudiep411/Django-React-to-do-List',
    demo: 'https://github.com/vudiep411/Django-React-to-do-List',
    visit: 'https://main.d5h9pd5jh16g1.amplifyapp.com/',
    id: 6,
  },

  
];

